site_name: fiware-sinfonier-docs
site_description: Sinfonier Documentation
docs_dir: docs/
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - 'Home': 'index.md'
  - 'Installation and Administration manual':
    - 'Installation': 'installation_and_administration_manual/installation.md'
    - 'Docker': 'installation_and_administration_manual/docker.md'
    - 'Stream processing: Sinfonier Architecture Overview': 'installation_and_administration_manual/streaming/stream_processing_sinfonier_architecture.md'
    - 'Stream processing: Sinfonier Drawer': 'installation_and_administration_manual/streaming/stream_processing_sinfonier_drawer.md'
    - 'Stream processing: Sinfonier API': 'installation_and_administration_manual/streaming/stream_processing_sinfonier_api.md'
    - 'Stream processing: Sinfonier BackEnd': 'installation_and_administration_manual/streaming/stream_processing_sinfonier_backend.md'
  - 'User and Programmer manual':
      - 'Introduction': 'user_and_programmer_manual/introduction.md'
      - 'Batch processing: Data management and I/O': 'user_and_programmer_manual/batch/data_management_and_io.md'
      - 'Batch processing: Requesting computing resources': 'user_and_programmer_manual/batch/request_computing_resources.md'
      - 'Batch processing: Using Hadoop and its ecosystem': 'user_and_programmer_manual/batch/using_hadoop_and_ecosystem.md'
      - 'Batch processing: OAuth2-protected REST APIs': 'user_and_programmer_manual/batch/oauth2_rest_apis.md'
      - 'Stream processing: Apche Storm & Sinfonier': 'user_and_programmer_manual/streaming/stream_processing_storm_sinfonier.md'
      - 'Stream processing: Sinfonier Topologies': 'user_and_programmer_manual/streaming/stream_processing_sinfonier_topologies.md'
      - 'Stream processing: Sinfonier Modules': 'user_and_programmer_manual/streaming/stream_processing_sinfonier_modules.md'