version: '2'
services:

  mongo:  
    image: mongo:3.2.9
    container_name: sinfonier_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    command: --smallfiles 
    restart: always
  # artifactory
  artifactory:  
    image: docker.bintray.io/jfrog/artifactory-oss
    hostname: artifactory
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory/data
      - artifactory_logs:/var/opt/jfrog/artifactory/logs
      - artifactory_etc:/var/opt/jfrog/artifactory/etc
    ports:
      - "8081:8081"
      - "5000-5002:5000-5002"
  zookeeper:
    image: 31z4/zookeeper:3.4.8
    container_name: zookeeper
    restart: always

  nimbus:
    image: 31z4/storm:0.10.1
    container_name: nimbus
    command: storm nimbus -c storm.log.dir="/logs" -c storm.zookeeper.servers="[\"zookeeper\"]" -c nimbus.host="nimbus" 
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 6627:6627
    volumes:
      - logs:/logs
    restart: always

  supervisor:
    image: 31z4/storm:0.10.1
    container_name: supervisor
    command: storm supervisor -c storm.log.dir="/logs" -c storm.zookeeper.servers="[\"zookeeper\"]" -c nimbus.host="nimbus" -c storm.local.hostname="sinfonier" 
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    volumes:
      - logs:/logs
    restart: always

  stormui:
    image: 31z4/storm:0.10.1
    container_name: stormui
    command: storm ui -c storm.log.dir="/logs" -c storm.zookeeper.servers="[\"zookeeper\"]" -c nimbus.host="nimbus"
    depends_on:
      - nimbus
      - zookeeper
    ports:
      - "8080:8080"
    links:
      - nimbus
      - zookeeper
    volumes:
      - logs:/logs
    restart: always

  logviewer:
    image: 31z4/storm:0.10.1
    container_name: logviewer
    command: storm logviewer -c storm.log.dir="/logs" -c storm.zookeeper.servers="[\"zookeeper\"]" -c nimbus.host="nimbus"  
    depends_on:
      - nimbus
      - zookeeper
    ports:
      - "8000:8000"
    links:
      - nimbus
      - zookeeper
    volumes:
      - logs:/logs
    restart: always

  backend:
    image: sinfonier/sinfonier-backend:latest
    container_name: sinfonier_backend
    depends_on: 
      - artifactory
    links:
      - artifactory
    environment:
        USER: sinfonier
  api:
    image: sinfonier/sinfonier-backend-api:latest
    container_name: sinfonier_api
    links:
      - mongo
      - logviewer:sinfonier
      - artifactory
      - stormui
    environment:
      - SINFONIER_API_NAME=docker
    ports:
      - "4000:4000"
    restart: always
  frontend:
    image: sinfonier/sinfonier-frontend:latest
    container_name: sinfonier_frontend
    links:
      - mongo
      - api
    ports:
      - "9000:9000"
volumes:
  mongodata: {}
  artifactory_data: {}
  artifactory_etc: {}
  artifactory_logs: {}
  logs: {}

